# Generated by Django 3.2.1 on 2021-05-05 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_created=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('crm', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(
                    blank=True, max_length=128, region='BR')),
                ('especialidade', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='DayScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=5)),
                ('agenda', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.dayschedule')),
            ],
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='core.medic', unique_for_date=models.DateField(auto_created=True)),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.dayscheduletime')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
