# Generated by Django 3.2.2 on 2021-05-09 21:19
import core.utilities
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('crm', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone',
                 phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128,
                                                                region='BR')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('dia',
                 models.DateField(auto_created=True, validators=[
                     core.utilities.validate_gte_today])),
                ('medico',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medic',
                                   unique_for_date='dia')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('horario', models.TimeField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='horarios', to='core.schedule')),
            ],
            options={
                'unique_together': {('agenda', 'horario')},
            },
        ),
        migrations.AddField(
            model_name='medic',
            name='especialidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='core.specialty'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('horario',
                 models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                      related_name='agendamento', to='core.scheduletime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
